# Generated by Django 6.0.2 on 2026-03-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('rent', models.IntegerField()),
                ('property_type', models.CharField(choices=[('Room', 'Room'), ('Flat', 'Flat'), ('Villa', 'Villa'), ('PG', 'PG')], max_length=20)),
                ('furnished', models.CharField(choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], max_length=20)),
                ('gender', models.CharField(choices=[('Any', 'Any'), ('Boys', 'Boys'), ('Girls', 'Girls'), ('Family', 'Family')], max_length=10)),
                ('smoking', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('verified', models.CharField(choices=[('Field Verified', 'Field Verified'), ('Video Verified', 'Video Verified'), ('Rural Verified', 'Rural Verified'), ('Basic Verified', 'Basic Verified')], default='Basic Verified', max_length=20)),
                ('scam_risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('compatibility', models.IntegerField(default=70)),
                ('image', models.CharField(default='🏠', max_length=10)),
                ('rooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('amenities', models.JSONField(default=list)),
                ('available', models.CharField(default='Immediate', max_length=50)),
                ('deposit', models.IntegerField()),
                ('description', models.TextField()),
                ('rural', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roommate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('profession', models.CharField(max_length=100)),
                ('compatibility', models.IntegerField(default=70)),
                ('sleep', models.CharField(choices=[('Night Owl', 'Night Owl'), ('Early Bird', 'Early Bird')], max_length=20)),
                ('cleanliness', models.IntegerField(default=5)),
                ('food', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20)),
                ('guests', models.CharField(choices=[('Often', 'Often'), ('Sometimes', 'Sometimes'), ('Rarely', 'Rarely')], max_length=20)),
                ('work_type', models.CharField(choices=[('WFH', 'WFH'), ('WFO', 'WFO'), ('Student', 'Student')], max_length=20)),
                ('budget', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
